services:
  backend:
    image: joshfung/reedr-backend:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "8000:3000"

  frontend:
    image: joshfung/reedr-frontend:v1.0.3
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000
    ports:
      - "8001:80"
