services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL
    # environment:
    #   - API_URL=$API_URL
    ports:
      # - "443:443"
      - "8001:80"
