services:
  backend:
    environment:
      - PORT=3000
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"

  frontend:
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8001:80"
