name: CD-Frontend

on: workflow_dispatch

env:
  FRONTEND_VERSION: "v2.0.1"

jobs:
  push-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::307349992383:role/Github_OIDC_IdP_Workflow_Tokens

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Update App Runner Service
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: aws apprunner update-service --service-arn ${{ secrets.FRONTEND_APP_RUNNER_ARN }} --source-configuration "ImageRepository={ImageIdentifier=$REGISTRY/reedr-frontend:$FRONTEND_VERSION, ImageRepositoryType=Ecr}"
