name: CI

on:
  push:
    branches:
      - main

env:
  BACKEND_VERSION: "v2.0.3"
  FRONTEND_VERSION: "v2.0.6"
  API_URL: "https://reedrapi.joshfung.dev"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build images
        run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg BACKEND_VERSION=$BACKEND_VERSION --build-arg FRONTEND_VERSION=$FRONTEND_VERSION --build-arg API_URL=$API_URL

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::307349992383:role/Github_OIDC_IdP_Workflow_Tokens

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Tag Images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag reedr-backend:latest $REGISTRY/reedr-backend:$BACKEND_VERSION
          docker tag reedr-frontend:latest $REGISTRY/reedr-frontend:$FRONTEND_VERSION

      - name: Push Images to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/reedr-backend:$BACKEND_VERSION
          docker push $REGISTRY/reedr-frontend:$FRONTEND_VERSION
