name: CI

on:
  push:
    branches:
      - main

env:
  BACKEND_VERSION: "v0.1.0"
  FRONTEND_VERSION: "v0.1.0"

# jobs:
#   build-images:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Build Backend Image
#         run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg BACKEND_VERSION=$BACKEND_VERSION backend

#       - name: Build Frontend Image
#         run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg FRONTEND_VERSION=$FRONTEND_VERSION frontend

#   push-images:
#     runs-on: ubuntu-latest
#     needs: build-images
#     permissions:
#       id-token: write
#     steps:
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           audience: sts.amazonaws.com
#           aws-region: ca-central-1
#           role-to-assume: arn:aws:iam::307349992383:role/Github_OIDC_IdP_Workflow_Tokens

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1
#         with:
#           mask-password: "true"

#       - name: Push Backend Image to ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: reedr-backend
#         run: docker push $REGISTRY/$REPOSITORY:$BACKEND_VERSION

#       # - name: push-frontend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Build Backend Image
      #   run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg BACKEND_VERSION=$BACKEND_VERSION backend

      # - name: Build Frontend Image
      #   run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg FRONTEND_VERSION=$FRONTEND_VERSION frontend

      - name: Build images
        run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg BACKEND_VERSION=$BACKEND_VERSION --build-arg FRONTEND_VERSION=$FRONTEND_VERSION

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::307349992383:role/Github_OIDC_IdP_Workflow_Tokens

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Push Backend Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: reedr-backend
        run: |
          docker push $REGISTRY/reedr-backend:$BACKEND_VERSION
          docker push $REGISTRY/reedr-frontend:$FRONTEND_VERSION

      # - name: push-frontend
