name: CI

on:
  push:
    branches:
      - main

env:
  BACKEND_VERSION: "v0.1.0"
  FRONTEND_VERSION: "v0.1.0"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: build-backend
        run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg BACKEND_VERSION=$BACKEND_VERSION backend

      - name: build-frontend
        run: docker compose -f ${{ github.workspace }}/compose.yaml build --build-arg FRONTEND_VERSION=$FRONTEND_VERSION frontend

  push-images:
    runs-on: ubuntu-latest
    needs: build-images
    permissions:
      id-token: write
    steps:
      - name: configure-aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::307349992383:role/Github_OIDC_IdP_Workflow_Tokens

      # - name: push-backend

      # - name: push-frontend
